language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
- ./gradlew setupCiWorkspace
after_deploy:
- ./gradlew curseforge
- ./gradlew bintrayUpload
deploy:
  provider: releases
  edge:
    branch: releases-fix
  skip_cleanup: true
  api_key:
    secure: TtIoo6z2ZbbYn7+QLUtzCjBFf7ZNfJeMW+YAvHBeElb9QEj/Vxt3U1SPg+U3XE5VEdUONQlGNrU0q3rq9emzQDXJdr30QjQ/XqykAnvEeVy2Eqn0EqdFq47t2fu/pEtyFHnUdCEWK26/Mj635fNV0PUfciDuh/k3Hxuk3DUBX6cokET31jwQQ2Bm37prhqq/PXWYPG1TN+ac/KL67qUh2c+eBHkQS/6+Z96B42cPnzCTPEcmjHwi0iWVzutxaF0agxYNnJSVuGFqQqKNTIwvQzusUZFcszRhF3JeOrDRbaJ3wtkTphBNAQCK6Ey67hwI5qVoDpzkIY7Oi3uvhZEtz987eRHkEzfnjUMq1WqLdq23NjvSQQTL5g2m12cjtAfBNtg1I3ixIu1RsSQCJ82mupkFXROkg7xYBrKWQnKH6OBtrIMTjVr/SthbeIn1vCF2fRf8laPv+tCdFe83o2nFsRSJqhyGTYh0O8ZARpPmOIX5CxQ3rm2EPr7y65pLvvsceu/KXzNrqRAmGy3HV2ngsOA637SvM2cWMLNq4DziDOx9nmqGC+FUhvx/wtXcSlwO9MUzdG4jatKdP3IIdEHEPYR2ZHNgMXgxvsIlHCZDuNkc2PpoOEKqDjpsqw29R4NuUmJ1WdEh/NELQYrgew9nnJTkPTUK0knarbwviU+8EX4=
  file_glob: true
  file: build/libs/*-sources.jar
  on:
    repo: Szewek/FL
    tags: true
env:
  global:
  - secure: N8LNt/+YW31RGXoz/+9F/hucp3ztYvIX4CbPZOc5efMhogHE8zIvr+Xis6sBIOQdqAVuUxyZtNbcJsJpTjn9aQEf3XsFErybPT73zkfbuXp4NLvyXfNup4IaTRuSbaADjxFeVLhrBQkYCDGLXqvH+Hs44H7PUtX9WmfF9ZNYoXfYn0qy8A2scQVUbj60wF7SSO9+MBkahlwsXt8o4ceL4HJ7V2FifkN7fyWVDNls7/14GImMCmIMDpdbwAZda8qCJm1//l18mjInCLIx4NYj4QokukirOIJCKLqZw4foFKfp5nodDcDfqTtWOeKP2niUIIQkuODoonNcRjVJG05IOFWDG2+hJdN35ZzNKyIbZKBbrSVecO+D3Tdv2nK08sEFUH0wFzQ40AruyvA9NvSbuqvI3aEkjao5LtOtk6bXDWM20ZjphPiWmZG3ffY0yTc6ldbmYA/IfonaJAPmuHG/couHu9UpaGAW8MNBWCeGtun8BeZt+3H4lhvfLZgFRaGhMbvkgJxGDKSmuj05vv4Ut0dgUy92NCsu2wjn3b+3yI1Y+hHz7pjIEgSEcb03vfM1Se8yIY39jhgFCHDSXD1Hs7SSPVgfJxqqvzBwtytJaRGIpeoZWmQVqDhOwE23q7oK1P1ghqX7Chu0gaCsE9zCQUDkAqX27PNqgKfXh4aQlUA=
  - secure: bpCsck9XMoVQC5z4/JmZnNZuknqPxfx6Tb26lf6NeQ6rSEZmHs99H3AIs0v9RCmDQuh71RTYrHf0M6DTORpxpIQWDD71UGBHY5gzA/JM51lyKeYeCDm9p5Uy3pihiA8jaXZ05pJL8/LLC9DmedVnUyiDFh7cDUY/dbvLH8TvTXgWWsU/I2HyY1U8Xb4yOzhZa3H6Wn5hmIwQzuYsgN1vUaS6yBZ7oi/fAes6sP4PctF7W/il2SoZfKWJ0Ik8t6L3KRAIQogJNydka719iAgs4TzlUC313sYxj+01nbWHuXhj6yJbdeV/Z/RRgGcBX24c6j2v1EITluJeoNAg4tE+TkaOJClb0eP7ht58fF13f3yrRjlGmMqOmoSB4BroUrEd4C32Z4EHbcZ5dpZ3VEYeA1bD1rQpt+IpfJY2W6+T/PLotxv3mRzn8GOLB5KIuGkFPxbPrIFnFxoPquvj948kRRUEauBiEFupcnqeH6qWLKOwgR+aTg8HNL5pTi7G/VEWXT6GRlnzBeuYYM/hGniqfpujDXWW7G73oohdcB+SfepU00YK8ZAH5bKR2AWgW0qU+NJDl5dmer2dyv2EfPsVeuew9YEGbTK5Q4C3gTySQHXO+wHrPghdQA7MrZ4HXXrvSyvyv+alC/WkumAhk7DluPc8Mf6jsJ+7r/L16bhQ1ag=
  - secure: FQzlF+szlgUCv1PSzlmxWo5S/Y49JCd8Vfix3C5aamA68z4mQxeNvww+beX6v/y5hsFKqHsiwgDBwBMMhvvmJx3BHbqacG49nGtm4Q/OQ4rsDnZ85H/RVtiLVwq5KU0XZuGlxxMw32AyUqcdFioC42u8eBHPPxKPlmrV1rQ+4PNiVIJxxdZKUqNRlgawKOp7Z3mzOivO2B0kQpoS0UmHOXtz9+fw7DYfcBxW7tBqINDrlxFH3QrwyJlARkztHjRRCaWaC+Jxz34pJp2/+9feoktZqum7wyoDxmtGArFTYHD6cY6PgxTeZYyngJgNlhBdcKyQOICObeJU6UgTKe/hXx1/n6clKt8mF7dqrf2RyjqsU2aLpR3cY3xElmji+iiOQGg2lgZkOKY254u1eBejZZWSETXuW7u8npeMy5rsLhLb4IKORHGKWf36ru4t0CbZDqTeP8Wg2E4QRIwBTySvqy6UQ5J61aGyqYeoDmuN5KC8iYiGwyI4SSvBcvqUclt1jQjRR6sosDqhpotUiVvkVZ82SPaigNfeT6DxEZ85kgvmcRNt3pXRn0DukznSd30yrQdRnOeluFBhl8nnSztmdCKOvMPpaMt/m6U00bvP+BavMSxWIo2VNUlJg1A8cNgXr1t3NK9DJ+n0sXTkrqno9uFAD9wQ49iUyqYU4GoUczo=
  - secure: VQ2IGHwFcbCiaFfctUZ7uJE38/SfIIqHlBDhoj7OBbmtLC7PRoHGMFOFn/OTdgiJ6DVRYUGmBHJaXg7Ul8x64Ky/r5AYZ66Z8+MKCtlCp2Hw2FzEE2p4001M2VmAZgSyHoou+yTMI/ygKmDDhM4lrkPEonwWFso7oXG5VsGGPviCwcXWpY51TWYWMAZZ+Kk/7Rt+5+yneh7abHd9ya5xrfEODwJTqJuyk0FnpTBx/EhzbtkdCbo4LxhLsmJYMSZn5Low/4N5bBHehG4dZIsDWYC3M0x5DGhaI0+c3jC/8FTA/DsRiyChPCFwBq2iyVLX1QwXOXFXlu0PZg7erKdXuvLPLvWqcoqhP4U+1eTThuGTyLk9GXeYsRvtiXN0OCTMilMEaUGZc/bwlIz7edeqMeSHvwUFThMZFVrEhvokqsBktdCUvmklhdorq7o/pZ5ld7iSpSvL1mBX1gxhzU8ckMfudxwEBJSRMQ2i8FL3O+sRjgv+4llE7ya/3KRodnK+x/J6t8yNBGQL44PuCwBwNWdl09VQbAMB9IkgNPnJgW5ujJv27eDHgh0FkLbpxGLD69G+Ij92jaxnyIVRmo73kmRf0uMoiZiTJ2i9PzV1ltbnMNXq4R0pLlZ0kKId6xwRGQdRxgHwbWf+ReLi4axbKiB1jJGEokW10KJe5WEzHK4=
